'use strict';

export const LOAD_ALL_FLIGHTS_SUCCESS = 'LOAD_ALL_FLIGHTS_SUCCESS';
export const LOAD_ALL_FLIGHTS_ERROR = 'LOAD_ALL_FLIGHTS_ERROR';
export const LOAD_ALL_FLIGHTS_REQUEST = 'LOAD_ALL_FLIGHTS_REQUEST';

export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const GET_TICKETS_ERROR = 'GET_TICKETS_ERROR';
export const GET_TICKETS_REQUEST = 'GET_TICKETS_REQUEST';