'use strict';

export const LOAD_ALL_FLIGHTS_SUCCESS = 'LOAD_ALL_FLIGHTS_SUCCESS';
export const LOAD_ALL_FLIGHTS_ERROR = 'LOAD_ALL_FLIGHTS_ERROR';
export const LOAD_ALL_FLIGHTS_REQUEST = 'LOAD_ALL_FLIGHTS_REQUEST';
